[package]
name = "axum-reverse-proxy"
version = "0.6.0"
edition = "2021"
description = "A flexible and efficient reverse proxy implementation for Axum web applications"
license = "MIT"
repository = "https://github.com/tom-lubenow/axum-reverse-proxy"
documentation = "https://docs.rs/axum-reverse-proxy"
readme = "README.md"
keywords = ["axum", "proxy", "reverse-proxy", "http", "web"]
categories = ["web-programming::http-server", "network-programming"]
authors = ["Tom Lubenow"]

[dependencies]
axum = { version = "^0.7", features = ["ws"] }
base64 = "^0.21"
bytes = "^1.5"
futures-util = "^0.3"
http = "^1.0"
http-body-util = "^0.1"
hyper = { version = "^1.5", features = ["full"] }
hyper-util = { version = "^0.1.10", features = ["full"] }
sha1 = "^0.10"
tokio = { version = "^1.35", features = ["full"] }
tokio-tungstenite = "^0.21"
tower = { version = "^0.4", features = ["full"] }
tracing = "^0.1"
url = "^2.5"

[dev-dependencies]
async-stream = "^0.3"
axum-server = { version = "^0.6", features = ["tls-rustls"] }
criterion = { version = "^0.5", features = ["async", "futures"] }
rcgen = "^0.12"
reqwest = { version = "^0.12", features = ["json", "rustls-tls", "http2"] }
serde_json = "^1.0"
tokio = { version = "^1.35", features = ["full", "test-util"] }
tower-buffer = "^0.3"
tower-http = { version = "^0.5", features = ["full"] }
tracing-subscriber = { version = "^0.3", features = ["env-filter"] }

[[bench]]
name = "proxy_bench"
harness = false

[[bench]]
name = "websocket_bench"
harness = false

[[example]]
name = "basic"
path = "examples/basic.rs"

[[example]]
name = "nested"
path = "examples/nested.rs"

[[example]]
name = "tower_middleware"
path = "examples/tower_middleware.rs"
