name: Benchmark

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GKE_CLUSTER: axum-proxy-benchmarks
  GKE_ZONE: us-central1-a
  PROJECT_ID: axum-proxy-benchmarks

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib>=3.8.0 pandas>=2.1.0 seaborn>=0.13.0 jq>=1.6.0 markdown>=3.5.0

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        token_format: 'access_token'
        workload_identity_provider: ''

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        install_components: 'gke-gcloud-auth-plugin'

    - name: Configure Docker
      run: |
        gcloud auth configure-docker gcr.io --quiet
        docker login -u oauth2accesstoken -p "$(gcloud auth print-access-token)" https://gcr.io

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Run benchmarks
      run: |
        chmod +x benchmarks/deploy.sh
        chmod +x benchmarks/run-comprehensive-benchmark.sh
        ./benchmarks/deploy.sh
        ./benchmarks/run-comprehensive-benchmark.sh

    - name: Generate plots
      run: |
        chmod +x benchmarks/scripts/generate_plots.py
        python benchmarks/scripts/generate_plots.py benchmarks/results/latest.json

    - name: Generate HTML report
      run: |
        chmod +x benchmarks/scripts/generate_report.py
        python benchmarks/scripts/generate_report.py

    - name: Deploy to benchmark-results branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: benchmark-results
        publish_dir: ./benchmark_results
        keep_files: false
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Update benchmark results [skip ci]' 